layout_spectrum: 0.3610764
name: RPKingLaw.com
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.5350438
  lightness: 0.2196496
  saturation: 0.479975
  rhythmicContrast: 0.2334168
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
typography_spectrum: 0.9017522
