layout_spectrum: 0.2284105
typography_spectrum: 0.3598332
color:
  lightness: 0.7941176
  brandStrength: 0.5350438
  saturation: 0.479975
  rhythmicContrast: 0.2334168
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: RPKingLaw.com
